#!/bin/bash -i
# Install virt-manager and configure it to use zfs storage pool (requires 10-zfs-client)

if ! which zfs &> /dev/null ; then
    sudo apt-get install -y virt-manager
fi

virsh pool-destroy default
virsh pool-undefine default

virsh pool-define-as default dir --target /virsh

virsh pool-build default
virsh pool-start default
virsh pool-autostart default

virsh pool-list --all
virsh pool-info default
