#!/bin/bash -i
# Generate ~/.git-credentials file from 1password (requires 50-1password)

if ! which op &> /dev/null; then
  echo "Couldn't find 1password client 'op'" >&2
  exit 1
fi

THIS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
REPO_DIR="$(git -C "$THIS_DIR" rev-parse --show-toplevel)"

TEMPLATE_FILE="$REPO_DIR/templates/.git-credentials"

"$REPO_DIR/stow/bin/bin/create-env-file" "$TEMPLATE_FILE" "$HOME/.git-credentials"
