#!/bin/bash


function del-prev-line {
  tput cuu1 && tput el
}

function prompt-yn {
  OPTIND=1
HELP=$(cat <<EOF
Prompts for y/n, executes action corresponding to user's choice

Usage:
    prompt-yn [-h] || [-p PROMPT_STRING -y EXPRESSION -n EXPRESSION]

Arguments:
    -h, --help    Print this message and exits
    -p, --prompt  Sets the prompt that the user will receive
    -y, --yes     Sets the command to be run if the user input is y/Y
    -n, --no      Sets the command to be run if the user input is n/N

Examples:
    Do something or exit:
    ynprompt ++
      -p "Do you really want to delete all the backups?" ++
      -y 'rm -rf ~/backups'  ++
      -n 'exit 0'

    Run 2 different commands:
    ynprompt -p "Are you cool?" -y 'echo You sure are!' -n 'echo I thought as much...'


    Exit with 2 different exit codes:
    ynprompt -p "Do you want to include FEATURE_NAME?" -y 'exit 1' -n 'exit 2'
    if [ \$? == 1 ]; then
        do_thing
    fi
EOF
)

 HELP=$(printf "%s" "$HELP" | sed -e 's/++/\\/' )
 PROMPT=""
 YESCOMMAND=""
 NOCOMMAND=""


 if [[ ! -n $1 ]]; then
   printf "%s\n" "$HELP"
   return 0
 fi
 while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|-\?)
      printf "%s\n" "$HELP"
      return 0
      ;;
    -p|--prompt)
      PROMPT="$2"
      shift 2
      ;;
    -y|--yes)
      YESCOMMAND="$2"
      shift 2
      ;;
    -n|--no)
      NOCOMMAND="$2"
      shift 2
      ;;
    --help)
      printf "%s\n" "$HELP"
      return 0
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "Invalid option: --${OPTARG}" >&2
      return 1
      ;;
    *)
      break
      ;;
   esac
  done

  if [ -n "$PROMPT" ]; then
    PROMPT="$PROMPT "
  fi

  if  [ ! -n "$PROMPT" ] || [ ! -n "$YESCOMMAND" ] || [ ! -n "$NOCOMMAND" ]; then
      echo "You must supply all required arguments: -p/--prompt, -y/--yes, -n/--no"
      return 2
  fi

  echo "$PROMPT(y/n)"
  while true; do
    read yn
    case $yn in
      [Yy]*)
	del-prev-line
        $YESCOMMAND
        break
        ;;
      [Nn]*)
	del-prev-line
        $NOCOMMAND
        break
        ;;
      *)
        echo "Please answer yes or no."
	del-prev-line
        ;;
    esac
  done

}

