#!/bin/bash

function THISDIR {
  echo "$(dirname "${BASH_SOURCE[1]}")"
}

function import-bash-libs {
  BASH_LIBS="$(find "$(dirname $BASH_SOURCE)" -maxdepth 1 -type f)"
  for lib in $BASH_LIBS; do
    . "$lib"
  done
}

